apiVersion: apps/v1
kind: Deployment
metadata:
  name: gig-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gig-service
  template:
    metadata:
      labels:
        app: gig-service
    spec:
      containers:
      - name: gig-service
        image: gig-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8082
        env:
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: http://eureka-server:8761/eureka/
---
apiVersion: v1
kind: Service
metadata:
  name: gig-service
spec:
  selector:
    app: gig-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
